[[redirects]]
  from = "/lab/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://lab.satisgraphtory2.com/*"
  to = "http://satisgraphtory2.com/lab/:splat"
  status = 200

[[redirects]]
  from = "https://lab.satisgraphtory2.com/*"
  to = "https://satisgraphtory2.com/lab/:splat"
  status = 200